//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public Nullable<int> IdEstadooCiudad { get; set; }
        public Nullable<int> IdDelegacionoMunicipio { get; set; }
        public Nullable<int> IdColonia { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public int IdDireccion { get; set; }
    
        public virtual Colonia Colonia { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
